/*********************************************************************************

** The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ********************************************************************************/
	
	var alert_arr = {       DELETE:'确定要删除选定的 ',
                                RECORDS:' 条记录？',
                                SELECT:'请选择至少一条记录',
                                DELETE_ACCOUNT:'删除这些客户将会删除它们相关的销售机会、报价单。确定要删除选定的 ',
                                DELETE_VENDOR:'删除这些供应商将会删除它们相关的采购订单。确定要删除选定的 ',
                                SELECT_MAILID:'请选择一个Email ID',
                                OVERWRITE_EXISTING_ACCOUNT1:'用选定的客户（',
                                OVERWRITE_EXISTING_ACCOUNT2:'）地址替换当前的地址吗？',
				                OVERWRITE_EXISTING_CONTACT1:'用选定的联系人（',
                                OVERWRITE_EXISTING_CONTACT2:'）地址替换当前的地址吗？',
                                MISSING_FIELDS:'必填内容不能为空：',
                                NOT_ALLOWED_TO_EDIT:'不允许编辑该字段',
                                NOT_ALLOWED_TO_EDIT_FIELDS:'不允许编辑这些字段',
                                COLUMNS_CANNOT_BE_EMPTY:'选择的列不能为空',
                                CANNOT_BE_EMPTY:' 不能为空',
                                CANNOT_BE_NONE:' 不能为空',
                                ENTER_VALID:'请输入正确的 ',
                                SHOULDBE_LESS:' 应小于 ',
                                SHOULDBE_LESS_EQUAL:' 应小于或等于 ',
                                SHOULDBE_EQUAL:' 应等于 ',
                                SHOULDBE_GREATER:' 应大于 ',
                                SHOULDBE_GREATER_EQUAL:' 应大于或等于 ',
                                INVALID:'无效的 ',
                                EXCEEDS_MAX:' 超过最大限制 ',
                                OUT_OF_RANGE:' 超出范围',
                                SHOULDNOTBE_EQUAL:' 不能等于 ',
                                PORTAL_PROVIDE_EMAILID:'请输入正确的Email Id以允许Portal用户',
                                ADD_CONFIRMATION:'确定要添加选定的 ',
                                ACCOUNTNAME_CANNOT_EMPTY:'AccountName 不能为空',
                                CANT_SELECT_CONTACTS:'无法从潜在客户选择相关联系人',
                                LBL_THIS:'这 ',
                                DOESNOT_HAVE_MAILIDS:' 没有任何 Email id',
                                ARE_YOU_SURE:'确定吗?',
                                DOESNOT_HAVE_AN_MAILID:'" 没有 Email id',
                                MISSING_REQUIRED_FIELDS:'以下字段不能为空: ',
                                READONLY:'这是只读的',
				SELECT_ATLEAST_ONE_USER:'请选择至少一个用户',
                                DISABLE_SHARING_CONFIRMATION:'确定要为选定的 ',
                                USERS:' 用户禁用共享 ?',
                                ENDTIME_GREATER_THAN_STARTTIME:'结束时间必须大于开始时间 ',
                                FOLLOWUPTIME_GREATER_THAN_STARTTIME:'跟进时间必须大于结束时间 ',
                                MISSING_EVENT_NAME:'事件名称不能为空',
                                EVENT_TYPE_NOT_SELECTED:'事件类型不能为空',
                                CLOSEDATE_CANNOT_BE_EMPTY:'关闭日期不能为空',
                                SITEURL_CANNOT_BE_EMPTY:'网站URL不能为空',
                                SITENAME_CANNOT_BE_EMPTY:'网站名称不能为空',
                                LISTPRICE_CANNOT_BE_EMPTY:'批发价不能为空',
                                INVALID_LIST_PRICE:'无效的批发价',
                                PROBLEM_ACCESSSING_URL:'访问URL出错: ',
                                CODE:' 代码: ',
                                WISH_TO_QUALIFY_MAIL_AS_CONTACT:'确定要把这封邮件转换为联系人？',
                                SELECT_ATLEAST_ONEMSG_TO_DEL:'请选择删除至少一条信息',
                                ERROR:'出错',
                                FIELD_TYPE_NOT_SELECTED:'未选择字段类型',
                                SPECIAL_CHARACTERS_NOT_ALLOWED:'标签不允许有特殊字符',
				SPECIAL_CHARACTERS:'特殊字符',
                                NOT_ALLOWED:'不允许. 请尝试其他值',
                                PICKLIST_CANNOT_BE_EMPTY:'下拉框选项不能为空',
                                DUPLICATE_VALUES_FOUND:'发现重复的值',
                                DUPLICATE_MAPPING_ACCOUNTS:'重复的客户映射！！',
                                DUPLICATE_MAPPING_CONTACTS:'重复的联系人映射！！',
                                DUPLICATE_MAPPING_POTENTIAL:'重复的销售机会映射！！',
                                ERROR_WHILE_EDITING:'编辑时出错',
                                CURRENCY_CHANGE_INFO:'修改货币成功',
                                CURRENCY_CONVERSION_INFO:'使用美元符号作为货币符号？ \n点击【确定】继续使用 $，点击【取消】更改汇率。',
                                THE_EMAILID: '在Email字段中的 email id "',
                                EMAIL_FIELD_INVALID:'" 是无效的',
                                MISSING_REPORT_NAME:'报表名称不能为空',
                                REPORT_NAME_EXISTS:'报名名称已存在，请尝试其他名称...',
                                WANT_TO_CHANGE_CONTACT_ADDR:'确定要更改这个客户的联系人地址吗？',
                                SURE_TO_DELETE:'确定要删除吗？',
				NO_PRODUCT_SELECTED:'没有选择产品。请选择至少一个产品',
                                VALID_FINAL_PERCENT:'请输入正确的折扣率',
                                VALID_FINAL_AMOUNT:'请输入正确的折扣金额',
                                VALID_SHIPPING_CHARGE:'请输入正确的运费和物流附加费',
                                VALID_ADJUSTMENT:'请输入正确的调整',
                                WANT_TO_CONTINUE:'要继续吗？',
                                ENTER_VALID_TAX:'请输入正确的税额',
                                VALID_TAX_NAME:'请输入正确的税名',
                                CORRECT_TAX_VALUE:'请输入正确的税额',
                                ENTER_POSITIVE_VALUE:'请输入正数',
                                LABEL_SHOULDNOT_EMPTY:'税的标签名不能为空',
                                NOT_VALID_ENTRY:'不正确，请输入正确的值',
                                VALID_DISCOUNT_PERCENT:'请输入正确的折扣率',
                                VALID_DISCOUNT_AMOUNT:'请输入正确的折扣金额',
                                SELECT_TEMPLATE_TO_MERGE:'请选择需要合并的模版',
				SELECTED_MORE_THAN_ONCE:'下列的条目被选择超过一次。',
				YES:'yes',
                                NO:'no',
                                MAIL:'mail',
				EQUALS:'等于',
				NOT_EQUALS_TO:'不等于',
				STARTS_WITH:'开始于',
				CONTAINS:'包含',	
				DOES_NOT_CONTAINS:'不包含',
				LESS_THAN:'小于',
				GREATER_THAN:'大于',
				LESS_OR_EQUALS:'小于等于',
				GREATER_OR_EQUALS:'大于等于',

				NO_SPECIAL_CHARS:'发货单不允许有特殊字符',
				PLS_SELECT_VALID_FILE:'请选择以下扩展名的文件：\n',
                                NO_SPECIAL:'不允许有特殊字符',
				NO_QUOTES:'引号 (\' ") 和加号 + 不允许',
				IN_PROFILENAME:' 在权限名中出现',
				IN_GROUPNAME:' 在部门名中出现',
				IN_ROLENAME:' 在职位名中出现',
                                VALID_TAX_PERCENT:'请输入正确的税率',
                                VALID_SH_TAX:'请输入正确的运费和物流附加费税 ',
				ROLE_DRAG_ERR_MSG:'不能把父节点移到子节点下',
				LBL_DEL:'del',
				VALID_DATA :' 请输入正确的数据 ,再试一次... ',
                                STDFILTER : '标准规则',
                                STARTDATE : '开始日期',
                                ENDDATE : '结束日期',
                                START_DATE_TIME : '开始时间',
                                START_TIME : '开始时间',
                                DATE_SHOULDNOT_PAST :'当前时间，对于状态为“已计划”的活动',
                                TIME_SHOULDNOT_PAST :'当前时间，对于状态为“已计划”的活动',
				LBL_AND : 'And',
				LBL_ENTER_VALID_PORT: '请输入正确的端口号',
				IN_USERNAME :' 在用户名中 ',
				LBL_ENTER_VALID_NO: '请输入正确的数字',
				LBL_PROVIDE_YES_NO: ' 无效的值。\n请输入 Yes 或 No',
				LBL_SELECT_CRITERIA: ' 无效的条件。\n请选择条件',
				// Added/Updated for vtiger CRM 5.0.4
				OPPORTUNITYNAME_CANNOT_BE_EMPTY:'销售机会名称不能为空',
                		OVERWRITE_EXISTING_ACCOUNT1:'用选定的客户（',
                		NAME_DESC:' 为文件夹名称和说明',
                		ENDS_WITH:'结束于',
                		SHARED_EVENT_DEL_MSG:'用户没有权限编辑/删除共享事件。',
                                                                                                                             

				LBL_WRONG_IMAGE_TYPE: '可用的文件类型： jpeg, png, jpg, pjpeg, x-png, gif',
				SELECT_MAIL_MOVE: '请选择一个邮件移动...',
				
				LBL_NOTSEARCH_WITHSEARCH_ALL:'你没有进行搜索，所有记录将会被导出从 ',
				LBL_NOTSEARCH_WITHSEARCH_CURRENTPAGE:'你没有进行搜索，但你选择了“导出搜索结果”和“导出当前页数据”选项，因此当前页数据将会被导出从 ',
				LBL_NO_DATA_SELECTED:'没有选择任何记录，请选择导出至少一条记录',
				LBL_SEARCH_WITHOUTSEARCH_ALL:'你进行了搜索，但你没有选择“导出不含搜索结果”和“导出所有数据”选项。\n点击【确定】导出所有数据，点击【取消】返回并选择其他导出选项。',
				STOCK_IS_NOT_ENOUGH : '库存不足',
				INVALID_QTY : '无效的数量',
				LBL_SEARCH_WITHOUTSEARCH_CURRENTPAGE:'你进行了搜索，但你没有选择“导出不含搜索结果”和“导出当前页数据”选项。\n点击【确定】导出当前页数据，点击【取消】返回并选择其他导出选项。',
				LBL_SELECT_COLUMN: ' 无效的列。\n请选择列',
				LBL_NOT_ACCESSIBLE : '无法访问',
				LBL_FILENAME_LENGTH_EXCEED_ERR: '文件名不能超过255个字符',
				LBL_DONT_HAVE_EMAIL_PERMISSION : '你没有访问Email字段的权限，因此你不能选择Email id',
				LBL_NO_FEEDS_SELECTED: '没有选择Feed网址',
				LBL_SELECT_PICKLIST:'请选择删除至少一个值',
				LBL_CANT_REMOVE:'不能能删除这些值',

				// Added after 5.0.4 GA
				
				/*For global add/delete in picklist*/
				LBL_GIVE_PICKLIST_VALUE:'请输入一些值替换选定的下拉框选项',
				LBL_SELECT_ROLE:'请选择至少一个职位',
				LBL_ADD_PICKLIST_VALUE:'请添加至少一个值',
				LBL_NO_VALUES_TO_DELETE: '没有任何值可以删除',

                /* For Duplicate merging feature */
				SAME_GROUPS: '只能合并同组的记录',
				ATLEAST_TWO: '请选择至少两条记录',
				MAX_THREE: '最多只能合并3条记录',
				//PARENT_RECORD: 'Select a record as parent record',  MergeFields.tpl Line:59
				MAX_RECORDS: '最多只能合并4条记录',
				CON_MANDATORY: '请选择必填字段：姓名',
				LE_MANDATORY: '请选择必填字段：姓名，公司',
				ACC_MANDATORY: '请选择必填字段：客户名',
				PRO_MANDATORY: '请选择必填字段：产品名',
				TIC_MANDATORY: '请选择必填字段：故障单标题',
				POTEN_MANDATORY: '请选择必填字段：销售机会名称',
				VEN_MANDATORY: '请选择必填字段：供应商名称',
				DEL_MANDATORY: '不能删除必填字段',
				
				/* For Multi-Currency Support */
				MSG_CHANGE_CURRENCY_REVISE_UNIT_PRICE: '所有单价的币种将会被修正为所选的货币，确定吗？',
				
				Select_one_record_as_parent_record : '请选择一个记录作为上级记录',
				RECURRING_FREQUENCY_NOT_PROVIDED : '没有输入重复频率',
				RECURRING_FREQNECY_NOT_ENABLED : '已经输入了重复频率，但没有“启用”重复',
				/* Added for Documents module */
				NO_SPECIAL_CHARS_DOCS:'不允许特殊字符，例如：引号、斜杠、加号+、百分号%、问号? 等等',
				FOLDER_NAME_TOO_LONG:'文件夹名太长，请重试！',
				FOLDERNAME_EMPTY:'文件夹名不能为空',
				DUPLICATE_FOLDER_NAME:'文件夹名称与现有的重复，请重试！',
				FOLDER_DESCRIPTION_TOO_LONG:'文件夹描述太长，请重试！',
				NOT_PERMITTED:'不允许执行该操作。',		
				
				ALL_FILTER_CREATION_DENIED:'自定义视图名称不能使用“All”，请改用别的名称。',
				OPERATION_DENIED:'拒绝执行该操作',
				EMAIL_CHECK_MSG: '保存Email字段为空可以禁止portal访问',
				IS_PARENT : '该产品有产品套餐，因此不能选择上级产品。',
				
				/*global actions on picklist*/
				PICKLIST_CANNOT_BE_EMPTY: '下拉框选项不能为空',
				DUPLICATE_VALUES_FOUND: '有重复的值',
				LBL_NO_ROLES_SELECTED: '没有选择职位，确定吗？',
				LBL_DUPLICATE_FOUND: '下拉框选项值重复 ',
				LBL_CANNOT_HAVE_EMPTY_VALUE: '不能替换为空值，要删除选项值请使用“删除”功能',
				LBL_DUPLICATE_VALUE_EXISTS: '有重复的值',
				LBL_WANT_TO_DELETE: '将会为所有职位删除选定的下拉框选项，确定吗？',
				LBL_DELETE_ALL_WARNING: '下拉框必须至少有一个选项',
				LBL_PLEASE_CHANGE_REPLACEMENT: '请更改替换的值，因为它即将被删除',
				
				/*layout Editor changes*/
				BLOCK_NAME_CANNOT_BE_BLANK : '区块名称不能为空',
				ARE_YOU_SURE_YOU_WANT_TO_DELETE : '确定要删除吗？',
				PLEASE_MOVE_THE_FIELDS_TO_ANOTHER_BLOCK : '请移动字段到其他区块',
				ARE_YOU_SURE_YOU_WANT_TO_DELETE_BLOCK : '确定要删除该区块吗？',
				LABEL_CANNOT_NOT_EMPTY : '标签不能为空',
				LBL_TYPEALERT_1 : '抱歉, 无法映射',
				LBL_WITH : '到',
				LBL_TYPEALERT_2 : '数据类型。提示：请映射相同的数据类型。',
				LBL_LENGTHALERT : '抱歉, 无法映射不同字符长度的字段。 提示：请映射相同或更长的字段。',
				LBL_DECIMALALERT : '抱歉, 无法映射不同小数位数的字段。 提示：请映射相同或更多小数位数的字段。',
				FIELD_IS_MANDATORY : '必填字段',
				FIELD_IS_ACTIVE : '启用',
				FIELD_IN_QCREATE : '在快速创建中可见',
				FIELD_IS_MASSEDITABLE : '在批量修改中可见',	
					
				IS_MANDATORY_FIELD : '是必填字段',
				CLOSEDATE_CANNOT_BE_EMPTY : '结束日期不能为空',
				AMOUNT_CANNOT_BE_EMPTY : '金额不能为空',
				ARE_YOU_SURE : '确定要删除吗？',
				LABEL_ALREADY_EXISTS : '标签已存在，请输入其他标签',
				LENGTH_OUT_OF_RANGE : '区块名称的长度应少于50个字符',
				LBL_SELECT_ONE_FILE : '请选择至少一个文件',
				LBL_UNABLE_TO_ADD_FOLDER : '无法添加文件夹，请重试。',
				LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE_FOLDER : '确定要删除该文件夹吗？',
				LBL_ERROR_WHILE_DELETING_FOLDER : '删除文件夹时出错，请稍后重试。',
				LBL_FILE_CAN_BE_DOWNLOAD : '文件可以下载',
				LBL_DOCUMENT_LOST_INTEGRITY:'该文档不可用，因为没有被标记为“启用”',
				LBL_DOCUMENT_NOT_AVAILABLE : '该文档不能下载',
				LBL_FOLDER_SHOULD_BE_EMPTY : '只能删除空文件夹！',
				
				LBL_PLEASE_SELECT_FILE_TO_UPLOAD : '请选择要上传的文件。',
				LBL_ARE_YOU_SURE_TO_MOVE_TO : '确定要移动这些文件到 ',
				LBL_FOLDER : ' 文件夹',
				LBL_UNABLE_TO_UPDATE : '无法更新！请重试',
				LBL_BLANK_REPLACEMENT: '不能用空值替代',
				
				LBL_IMAGE_DELETED : '图片已删除',
				
				/* Tooltip management */
				ERR_FIELD_SELECTION : '选择字段时出错',
				
				/* Inventory validation strings */
				NO_LINE_ITEM_SELECTED : '没有选择列表项，请选择至少一个列表项。',
				LINE_ITEM : '列表项',
				LIST_PRICE: '批发价',
				
				/* Webmails */
				LBL_PRINT_EMAIL : '打印', 
				LBL_DELETE_EMAIL : '删除', 
				LBL_DOWNLOAD_ATTACHMENTS : '下载附件', 
				LBL_QUALIFY_EMAIL : '转换', 
				LBL_FORWARD_EMAIL : '转发', 
				LBL_REPLY_TO_SENDER : '回复发送人', 
				LBL_REPLY_TO_ALL : '全部回复',
				
				LBL_WIDGET_HIDDEN : '隐藏组件',
				LBL_RESTORE_FROM_PREFERENCES : '可以在“个人设置”里面恢复它',
				ERR_HIDING : '隐藏时出错',
				MSG_TRY_AGAIN : '请重试',
				
				MSG_ENABLE_SINGLEPANE_VIEW : '启用 单面板视图',
				MSG_DISABLE_SINGLEPANE_VIEW : '禁用 单面板视图',
				
				MSG_FTP_BACKUP_DISABLED : '禁用 FTP备份',
				MSG_LOCAL_BACKUP_DISABLED : '禁用 本地备份',
				MSG_FTP_BACKUP_ENABLED : '启用 FTP备份',
				MSG_LOCAL_BACKUP_ENABLED : '启用 本地备份',
				MSG_CONFIRM_PATH : '请确保备份路径信息无误',
				MSG_CONFIRM_FTP_DETAILS : '请确保FTP服务器信息无误',
				
				START_PERIOD_END_PERIOD_CANNOT_BE_EMPTY : '开始时期 或 结束时期 不能为空',
				
				/* added to fix i18n issues with home page*/
				LBL_ADD: '添加 ',
				Module: '模块',
				DashBoard: '图表',
				RSS: 'RSS新闻',
				Default: '默认',
				Notebook: '记事本',
				SPECIAL_CHARS:'\\ / < > + \' " ',
				
				BETWEEN: '之间',
				BEFORE: '之前',
				AFTER: '之后',
				'ERROR_DELETING_TRY_AGAIN': '删除时出错，请重试',
				'LBL_ENTER_WINDOW_TITLE': '请输入窗口标题',
				'LBL_SELECT_ONLY_FIELDS': '请仅选择两个字段。',
				'LBL_ENTER_RSS_URL':'请输入RSS URL',
				'LBL_ADD_HOME_WIDGET': '无法添加首页组件，请重试',
	'LBL_DEFAULT_VALUE_FOR_THIS_FIELD' : '字段默认值',

	'RECIPIENTS_CANNOT_BE_EMPTY' : '选定的收件人不能为空',
	'VALID_SCANNER_NAME' : '请输入一个有效的扫描器的名称（它应该是唯一的字符和数字的组合）',
	'ERR_SAME_SOURCE_AND_TARGET' : '源字段和目标字段不应该是相同的',
	'ERR_ATLEAST_ONE_VALUE_FOR' : '你需要至少选择一个值',
	'ERR_SELECT_MODULE_FOR_DEPENDENCY' : '请选择一个模块添加依赖关系',

	'LBL_SIZE_SHOULDNOTBE_GREATER':'文件大小应不大于 ', //added for upload error message
	'LBL_MAX_SIZE':'最大上传大小为', //added for display file size limit
	'LBL_FILESIZEIN_MB':'MB', // added to show filesize limit in MB
	'LBL_FILESIZEIN_KB':'KB', // added to show filesize limit in KB
	'LBL_FILESIZEIN_B':'B', // added to show filesize limit in B
	//Contexual help page
    'LBL_HELP_TITLE' : '帮助',
    'LBL_WIKI_TITLE' : '手册',
    'LBL_FAQ_TITLE'   : 'FAQ',
    'LBL_VIDEO_TITLE' : '视频',
    'LBL_CLOSE_TITLE' : '关闭',
	'LBL_SELECT':'选择要显示的预设小部件',

	'ERR_SELECT_ATLEAST_ONE_MERGE_CRITERIA_FIELD' : '选择至少一个字段进行合并操作',
	'ERR_PLEASE_MAP_MANDATORY_FIELDS' : '请映射以下强制性字段',
	'ERR_MAP_NAME_ALREADY_EXISTS' : '映射名称已经存在，请给一个不同的名称',
	'ERR_MAP_NAME_CANNOT_BE_EMPTY' : '映射名称不能为空',
	'ERR_FIELDS_MAPPED_MORE_THAN_ONCE' : '以下字段映射不止一次请检查映射.',

	//arror messages for lead conversion
	'ERR_SELECT_EITHER':'选择组织或联系人转换潜在客户',
	'ERR_SELECT_ACCOUNT':'选择组织进行',
	'ERR_SELECT_CONTACT':'选择联系人进行',
	'ERR_MANDATORY_FIELD_VALUE':'强制性字段的值缺失',
	'ERR_POTENTIAL_AMOUNT':'销售机会金额必须是一个数字',
	'ERR_EMAILID':'请输入有效的电子邮件ID',
	'ERR_TRANSFER_TO_ACC':'应选择组织（客户）转移相关记录',
	'ERR_TRANSFER_TO_CON':'联系人应选择转移移相关记录 ',
	'SURE_TO_DELETE_CUSTOM_MAP':'你确定要删除该字段映射?',
	'LBL_CLOSE_DATE':'关闭日期',
	'LBL_EMAIL':'Email',
	'MORE_THAN_500' : '你选择超过500个记录进行这个动作，它可能需要更长的时间，你确定要继续吗？',
	'LBL_MAPPEDALERT':'字段已经进行映射'
			};
